### ISSUE TITLE
When any ancestor node of the AnnotateCanvas node has their position anywhere but the World origin, drawing will be offset

### ISSUE THREAD

**Issue by golddotasksquestions** [zarstensen/GodotAnnotate#14]
Unfortunately this makes it impossible to move the AnnotateCanvas node anywhere:

https://github.com/zarstensen/GodotAnnotate/assets/47016402/520984b6-355d-4150-8f39-7a050130e642

**Comment by zarstensen** [comment]
Hi @golddotasksquestions, good catch but this should actually already have been fixed by #11, the fix has just not been released as part of a version yet, so closing this as a duplicate.
